title:
  Using Biologically Plausible Long-Term Memory to Address Catastrophic
  Forgetting in AI,
description:
  Bommer, S., Troquay, E. P. M., Zhang, X. & Starace, G. (2022) - ABC Summer
  School 2022
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
